"""option strike snapshot

Revision ID: d1b6e4daf936
Revises: 0001_baseline
Create Date: 2026-07-30 11:50:50.661603+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import mios.persistence.types

revision: str = "d1b6e4daf936"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option_strike_snapshot",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column(
            "option_type", sa.Enum("CE", "PE", name="option_type"), nullable=False
        ),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("oi", sa.Integer(), nullable=False),
        sa.Column("oi_change", sa.Integer(), nullable=False),
        sa.Column("premium", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("premium_change", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("volume_change", sa.Integer(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "long_buildup",
                "short_buildup",
                "long_unwinding",
                "short_covering",
                name="classification",
            ),
            nullable=True,
        ),
        sa.Column(
            "captured_at",
            mios.persistence.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            mios.persistence.types.UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mios.persistence.types.UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_option_strike_snapshot")),
    )
    op.create_index(
        op.f("ix_option_strike_snapshot_captured_at"),
        "option_strike_snapshot",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_option_strike_snapshot_lookup",
        "option_strike_snapshot",
        ["symbol", "strike", "option_type", "captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_option_strike_snapshot_symbol"),
        "option_strike_snapshot",
        ["symbol"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_option_strike_snapshot_symbol"), table_name="option_strike_snapshot"
    )
    op.drop_index(
        "ix_option_strike_snapshot_lookup", table_name="option_strike_snapshot"
    )
    op.drop_index(
        op.f("ix_option_strike_snapshot_captured_at"),
        table_name="option_strike_snapshot",
    )
    op.drop_table("option_strike_snapshot")
    # ### end Alembic commands ###

    # PostgreSQL does not drop named ENUM types when their table is dropped, so
    # they must be removed explicitly or a re-upgrade fails with "type already
    # exists". Autogenerate does not emit these.
    sa.Enum(name="classification").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="option_type").drop(op.get_bind(), checkfirst=True)
