"""Reusable model mixins.

Each mixin is independent and contributes one concern, so a model composes only
what it needs. They add columns and storage behaviour only — never business
meaning.

`declared_attr` defers column construction until the mapped class is built, so
each subclass receives its own `Column` object rather than sharing one.
"""

import datetime as dt
from typing import Any
from uuid import UUID

from sqlalchemy import Index, Integer, func, text
from sqlalchemy.orm import Mapped, declared_attr, mapped_column

from mios.persistence.types import ActorType, UTCDateTime, UUIDType
from mios.persistence.utils import INITIAL_VERSION, new_uuid, utc_now


class IdentityMixin:
    """UUID primary key.

    The identifier is generated by the application so it is known before the
    row is flushed. `server_default` covers inserts issued outside the ORM. Per
    the Immutable Identifiers rule in `docs/24-database-design.md`, the value is
    never reassigned once set.
    """

    @declared_attr
    @classmethod
    def id(cls) -> Mapped[UUID]:
        """Primary key."""
        return mapped_column(
            UUIDType,
            primary_key=True,
            default=new_uuid,
            server_default=text("gen_random_uuid()"),
        )


class TimestampMixin:
    """Creation and last-modification timestamps in UTC.

    Both server- and Python-side defaults are set: the database clock is
    authoritative for new rows, while `onupdate` keeps `updated_at` accurate for
    ORM-issued updates.
    """

    @declared_attr
    @classmethod
    def created_at(cls) -> Mapped[dt.datetime]:
        """Instant the record was first written."""
        return mapped_column(
            UTCDateTime,
            nullable=False,
            default=utc_now,
            server_default=func.now(),
        )

    @declared_attr
    @classmethod
    def updated_at(cls) -> Mapped[dt.datetime]:
        """Instant the record was last modified."""
        return mapped_column(
            UTCDateTime,
            nullable=False,
            default=utc_now,
            server_default=func.now(),
            onupdate=utc_now,
        )


class AuditMixin:
    """Actors who created and last modified the record.

    Nullable: records written by platform processes rather than a user have no
    actor. Populating these columns is the caller's responsibility — persistence
    does not resolve identity.
    """

    @declared_attr
    @classmethod
    def created_by(cls) -> Mapped[str | None]:
        """Return the actor that created the record."""
        return mapped_column(ActorType, nullable=True, default=None)

    @declared_attr
    @classmethod
    def updated_by(cls) -> Mapped[str | None]:
        """Return the actor that last modified the record."""
        return mapped_column(ActorType, nullable=True, default=None)


class SoftDeleteMixin:
    """Logical deletion via a nullable timestamp.

    A `NULL` `deleted_at` means the record is live. Readers must filter on it
    explicitly; this mixin adds no automatic query filtering, keeping the
    behaviour predictable.
    """

    @declared_attr
    @classmethod
    def deleted_at(cls) -> Mapped[dt.datetime | None]:
        """Instant the record was soft deleted, or `None` while live."""
        return mapped_column(UTCDateTime, nullable=True, default=None, index=True)

    @property
    def is_deleted(self) -> bool:
        """Whether the record is currently soft deleted."""
        return self.deleted_at is not None

    def soft_delete(self, *, at: dt.datetime | None = None) -> None:
        """Mark the record as deleted, leaving an already-deleted record as is."""
        if self.deleted_at is None:
            self.deleted_at = at or utc_now()

    def restore(self) -> None:
        """Clear the deletion marker."""
        self.deleted_at = None


class VersionMixin:
    """Optimistic locking via a monotonically increasing version counter.

    SQLAlchemy increments `version` on every flush and adds it to the `WHERE`
    clause of updates, raising `StaleDataError` when a concurrent writer has
    already advanced it.

    A model combining this mixin with its own `__mapper_args__` must merge in
    `version_id_col`, since the mixin's `declared_attr` would otherwise be
    overridden.
    """

    @declared_attr
    @classmethod
    def version(cls) -> Mapped[int]:
        """Row version, starting at `INITIAL_VERSION`."""
        return mapped_column(
            Integer,
            nullable=False,
            default=INITIAL_VERSION,
            server_default=text(str(INITIAL_VERSION)),
        )

    @declared_attr.directive
    @classmethod
    def __mapper_args__(cls) -> dict[str, Any]:
        """Register `version` as the mapper's version column."""
        return {"version_id_col": cls.version}


def soft_delete_index(table_name: str, *columns: str) -> Index:
    """Build a partial index restricted to rows that are not soft deleted.

    Uniqueness on a soft-deleting table usually has to exclude deleted rows, so
    a value can be reused after deletion. Requires `SoftDeleteMixin`.
    """
    return Index(
        f"ix_{table_name}_{'_'.join(columns)}_live",
        *columns,
        unique=True,
        postgresql_where=text("deleted_at IS NULL"),
    )
