import type { DashboardResponse } from "@/types/dashboard";

/** A representative healthy, qualified-trade dashboard payload for tests. */
export const dashboardFixture: DashboardResponse = {
  connection_state: "connected",
  authentication: "CONNECTED",
  data_source: "simulator",
  market: {
    spot: "25184.25",
    atm_strike: "25200", // round(25184.25 / 50) * 50
    strike_step: 50,
    change: "86.25",
    change_percent: 0.34,
    status: "LIVE",
    updated_at: "2026-01-01T09:42:15+00:00",
  },
  narrative: {
    tone: "bullish",
    headline:
      "🟢 Bulls are gradually taking control. Fresh call buying is visible at 25150 and 25200. The underlying is breaking out, and MIOS has qualified 25150 CE.",
    statements: [
      "Bulls are in control.",
      "Buyer participation increasing.",
      "Momentum is increasing.",
      "Price is breaking out.",
      "Trade qualified.",
    ],
  },
  dominance: {
    control: "bulls",
    buyers_pct: 78,
    writers_pct: 22,
    ce_dominance: "Strong",
    pe_dominance: "Weak",
    control_shift_from: "Neutral",
    control_shift_to: "Bullish",
  },
  qualification: {
    decision: "BUY_CE",
    qualified: true,
    strike: "25150",
    option_type: "CE",
    classification: "long_buildup",
    confidence: 100,
    band: "Very High",
    gates: [
      {
        name: "Market Regime",
        passed: true,
        reason: "Confirmed breakout.",
        weight: 30,
        mandatory: true,
      },
      {
        name: "Options Participation",
        passed: true,
        reason: "Long Buildup at 25150 CE.",
        weight: 30,
        mandatory: true,
      },
      {
        name: "CE vs PE Control",
        passed: true,
        reason: "CE side is in control.",
        weight: 25,
        mandatory: true,
      },
      {
        name: "Strike Quality",
        passed: true,
        reason: "Liquid and 1 step(s) from ATM.",
        weight: 15,
        mandatory: false,
      },
    ],
    failed_gates: [],
    reasons: [
      "OI ↑ 18.0%",
      "Premium ↑ 9.0%",
      "Volume ↑ 34.0%",
      "Unusual activity flagged",
      "Buyers dominant",
      "Bulls control market",
      "No contradiction",
      "Trend supports options activity",
    ],
    best_candidate: {
      strike: "25150",
      option_type: "CE",
      classification: "long_buildup",
      qualification: 91,
      reason: "Qualified: option activity and market structure aligned.",
    },
  },
  context: {
    controlling_side: "bulls",
    dominant_participant: "buyers",
    momentum: "increasing",
    momentum_strengthening: true,
    momentum_weakening: false,
    structure_trend: "uptrend",
    structure_validates_options: true,
    contradiction: null,
    immediate_support: "25000",
    immediate_resistance: "25200",
    structure_pattern: "breakout",
    swing_high: "25220",
    swing_low: "24980",
    swings: [
      { timestamp: "2026-01-01T09:20:00+00:00", price: "24980", label: "HL" },
      { timestamp: "2026-01-01T09:35:00+00:00", price: "25220", label: "HH" },
    ],
    gap_classification: "gap_up",
    gap_pct: 0.54,
    statements: ["Bulls control the market."],
    evidence: ["Net CE OI change: +12,000"],
  },
  ce_pe: {
    stronger_side: "CE",
    writer_active_strikes: ["25000"],
    buyer_active_strikes: ["25150"],
    control_shifting: false,
    shift_description: null,
    important_strikes: ["25150"],
    evidence: ["Net CE OI change: +12,000"],
  },
  // Ranked strongest-OI strikes, clustered around ATM (25200) so the
  // Participation Radar's ATM±2 window (25100–25300) has a two-sided grid.
  participation: [
    {
      rank: 1,
      strike: "25200",
      option_type: "PE",
      classification: "short_buildup",
      oi_change: 3000,
      oi_change_pct: 6.2,
      premium_change_pct: -2.0,
      volume_change_pct: 28.0,
    },
    {
      rank: 2,
      strike: "25250",
      option_type: "PE",
      classification: "short_buildup",
      oi_change: 2600,
      oi_change_pct: 5.35,
      premium_change_pct: -1.29,
      volume_change_pct: 40.4,
    },
    {
      rank: 3,
      strike: "25150",
      option_type: "CE",
      classification: "long_buildup",
      oi_change: 1400,
      oi_change_pct: 3.54,
      premium_change_pct: 9.0,
      volume_change_pct: 34.0,
    },
    {
      rank: 4,
      strike: "25200",
      option_type: "CE",
      classification: "short_covering",
      oi_change: 900,
      oi_change_pct: 2.1,
      premium_change_pct: 4.5,
      volume_change_pct: 12.0,
    },
    {
      rank: 5,
      strike: "25100",
      option_type: "PE",
      classification: "long_unwinding",
      oi_change: -1200,
      oi_change_pct: -3.1,
      premium_change_pct: -5.0,
      volume_change_pct: 8.0,
    },
  ],
  option_chain: [
    {
      strike: "25150",
      option_type: "CE",
      premium: "142.50",
      oi: 40911,
      oi_change: 1400,
      volume: 18076,
      classification: "long_buildup",
      unusual_flags: ["oi_change", "volume_change"],
      recommendation_flag: true,
    },
    {
      strike: "25200",
      option_type: "CE",
      premium: "98.10",
      oi: 30250,
      oi_change: -800,
      volume: 9021,
      classification: "short_covering",
      unusual_flags: [],
      recommendation_flag: false,
    },
    {
      strike: "25000",
      option_type: "PE",
      premium: "88.25",
      oi: 51200,
      oi_change: 2600,
      volume: 22110,
      classification: "short_buildup",
      unusual_flags: ["oi_velocity"],
      recommendation_flag: false,
    },
  ],
  engine: {
    healthy: true,
    pipeline_runtime_ms: 1.42,
    data_age_seconds: 0.6,
  },
};

/** A no-trade payload: mandatory gate fails, best candidate still shown. */
export const noTradeFixture: DashboardResponse = {
  ...dashboardFixture,
  narrative: {
    tone: "neutral",
    headline:
      "⚪ Neither side has taken control. The underlying is inside a range, so MIOS is standing aside until clearer signals appear.",
    statements: [
      "Neither side is in control.",
      "Momentum is neutral.",
      "Price is inside a range.",
      "Trade quality improving.",
    ],
  },
  dominance: {
    control: "neutral",
    buyers_pct: 50,
    writers_pct: 50,
    ce_dominance: "Balanced",
    pe_dominance: "Balanced",
    control_shift_from: "Neutral",
    control_shift_to: "Neutral",
  },
  qualification: {
    decision: "NO_TRADE",
    qualified: false,
    strike: null,
    option_type: null,
    classification: null,
    confidence: 70,
    band: "Medium",
    gates: [
      {
        name: "Market Regime",
        passed: false,
        reason: "No trend or breakout; market is sideways/choppy.",
        weight: 30,
        mandatory: true,
      },
      {
        name: "Options Participation",
        passed: true,
        reason: "Long Buildup at 25150 CE.",
        weight: 30,
        mandatory: true,
      },
      {
        name: "CE vs PE Control",
        passed: true,
        reason: "CE side is in control.",
        weight: 25,
        mandatory: true,
      },
      {
        name: "Strike Quality",
        passed: true,
        reason: "Liquid and 1 step(s) from ATM.",
        weight: 15,
        mandatory: false,
      },
    ],
    failed_gates: ["Market Regime"],
    reasons: ["OI ↑ 18.0%", "Buyers dominant"],
    best_candidate: {
      strike: "25150",
      option_type: "CE",
      classification: "long_buildup",
      qualification: 55,
      reason: "Good option activity, but market structure has not confirmed yet.",
    },
  },
};

/** A not-connected payload: no session, empty market. */
export const notConnectedFixture: DashboardResponse = {
  connection_state: "not_connected",
  authentication: "NOT_AUTHENTICATED",
  data_source: "none",
  market: {
    spot: null,
    atm_strike: null,
    strike_step: 50,
    change: null,
    change_percent: null,
    status: "CLOSED",
    updated_at: null,
  },
  narrative: null,
  dominance: null,
  qualification: null,
  participation: [],
  context: null,
  ce_pe: null,
  option_chain: [],
  engine: { healthy: false, pipeline_runtime_ms: null, data_age_seconds: null },
};
